### ISSUE TITLE
configparser.NoSectionError: No section: 'keybinds

### ISSUE THREAD

**Issue by Allmight0000** [vike256/Unibot#20]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Unibot-1.4.2\Unibot-1.4.2\src\main.py", line 6, in <module>
    import cfg
  File "C:\Users\Administrator\Downloads\Unibot-1.4.2\Unibot-1.4.2\src\cfg.py", line 254, in <module>
    read_config()
  File "C:\Users\Administrator\Downloads\Unibot-1.4.2\Unibot-1.4.2\src\cfg.py", line 204, in read_config
    key_reload_config = configFile.get('keybinds', 'key_reload_config')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'keybinds'

**Comment by vike256** [comment]
Forgot that config.ini updates were skipped by git. I'll fix in a second

**Comment by vike256** [comment]
Should work now. Download v1.4.3

**Comment by Allmight0000** [comment]
you have a discord man?
